//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UXM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UXM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /breakobj/m10_02_00_00.breakobj
        ////breakobj/m10_04_00_00.breakobj
        ////breakobj/m10_10_00_00.breakobj
        ////breakobj/m10_14_00_00.breakobj
        ////breakobj/m10_15_00_00.breakobj
        ////breakobj/m10_16_00_00.breakobj
        ////breakobj/m10_17_00_00.breakobj
        ////breakobj/m10_18_00_00.breakobj
        ////breakobj/m10_19_00_00.breakobj
        ////breakobj/m10_23_00_00.breakobj
        ////breakobj/m10_25_00_00.breakobj
        ////breakobj/m10_27_00_00.breakobj
        ////breakobj/m10_29_00_00.breakobj
        ////breakobj/m10_30_00_00.breakobj
        ////breakobj/m10_31_00_00.breakobj
        ////breakobj/m10_32_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DarkSouls2Dictionary {
            get {
                return ResourceManager.GetString("DarkSouls2Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;game_info&gt;
        ///  &lt;required_gb&gt;16&lt;/required_gb&gt;
        ///  &lt;bhd5_game&gt;DarkSouls2&lt;/bhd5_game&gt;
        ///  &lt;archives&gt;
        ///    &lt;archive&gt;GameDataEbl&lt;/archive&gt;
        ///    &lt;archive&gt;HqChrEbl&lt;/archive&gt;
        ///    &lt;archive&gt;HqMapEbl&lt;/archive&gt;
        ///    &lt;archive&gt;HqObjEbl&lt;/archive&gt;
        ///    &lt;archie&gt;HqPartsEbl&lt;/archie&gt;
        ///  &lt;/archives&gt;
        ///  &lt;backup_dirs&gt;
        ///    &lt;backup&gt;param&lt;/backup&gt;
        ///    &lt;backup&gt;sfx&lt;/backup&gt;
        ///    &lt;backup&gt;sfx_hq&lt;/backup&gt;
        ///    &lt;backup&gt;sound&lt;/backup&gt;
        ///  &lt;/backup_dirs&gt;
        ///  &lt;delete_dirs&gt;
        ///    &lt;delete&gt;_unknown&lt;/delete&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DarkSouls2GameInfo {
            get {
                return ResourceManager.GetString("DarkSouls2GameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /action/eventnameid.txt
        ////action/script/c0000.hks
        ////action/script/c0001.hks
        ////action/script/c0002.hks
        ////action/script/c0004.hks
        ////action/script/c0006.hks
        ////action/script/c0100.hks
        ////action/script/c1030.hks
        ////action/script/c1040.hks
        ////action/script/c1041.hks
        ////action/script/c1050.hks
        ////action/script/c1060.hks
        ////action/script/c1070.hks
        ////action/script/c1090.hks
        ////action/script/c1100.hks
        ////action/script/c1105.hks
        ////action/script/c1110.hks
        ////action/script/c1120.hks
        ////action/script/c1130.hks
        ////action/script/c113 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DarkSouls3Dictionary {
            get {
                return ResourceManager.GetString("DarkSouls3Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;game_info&gt;
        ///  &lt;required_gb&gt;25&lt;/required_gb&gt;
        ///  &lt;bhd5_game&gt;DarkSouls3&lt;/bhd5_game&gt;
        ///  &lt;archives&gt;
        ///    &lt;archive&gt;Data1&lt;/archive&gt;
        ///    &lt;archive&gt;Data2&lt;/archive&gt;
        ///    &lt;archive&gt;Data3&lt;/archive&gt;
        ///    &lt;archive&gt;Data4&lt;/archive&gt;
        ///    &lt;archive&gt;Data5&lt;/archive&gt;
        ///    &lt;archive&gt;DLC1&lt;/archive&gt;
        ///    &lt;archive&gt;DLC2&lt;/archive&gt;
        ///  &lt;/archives&gt;
        ///  &lt;backup_dirs&gt;
        ///    &lt;backup&gt;sound&lt;/backup&gt;
        ///  &lt;/backup_dirs&gt;
        ///  &lt;delete_dirs&gt;
        ///    &lt;delete&gt;_unknown&lt;/delete&gt;
        ///    &lt;delete&gt;action&lt;/delete&gt;
        ///    &lt;delete&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DarkSouls3GameInfo {
            get {
                return ResourceManager.GetString("DarkSouls3GameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /breakobj/m10_02_00_00.breakobj
        ////breakobj/m10_04_00_00.breakobj
        ////breakobj/m10_10_00_00.breakobj
        ////breakobj/m10_14_00_00.breakobj
        ////breakobj/m10_15_00_00.breakobj
        ////breakobj/m10_16_00_00.breakobj
        ////breakobj/m10_17_00_00.breakobj
        ////breakobj/m10_18_00_00.breakobj
        ////breakobj/m10_19_00_00.breakobj
        ////breakobj/m10_23_00_00.breakobj
        ////breakobj/m10_25_00_00.breakobj
        ////breakobj/m10_27_00_00.breakobj
        ////breakobj/m10_29_00_00.breakobj
        ////breakobj/m10_30_00_00.breakobj
        ////breakobj/m10_31_00_00.breakobj
        ////breakobj/m10_32_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScholarDictionary {
            get {
                return ResourceManager.GetString("ScholarDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;game_info&gt;
        ///  &lt;required_gb&gt;18&lt;/required_gb&gt;
        ///  &lt;bhd5_game&gt;DarkSouls2&lt;/bhd5_game&gt;
        ///  &lt;archives&gt;
        ///    &lt;archive&gt;GameDataEbl&lt;/archive&gt;
        ///    &lt;archive&gt;LqChrEbl&lt;/archive&gt;
        ///    &lt;archive&gt;LqMapEbl&lt;/archive&gt;
        ///    &lt;archive&gt;LqObjEbl&lt;/archive&gt;
        ///    &lt;archie&gt;LqPartsEbl&lt;/archie&gt;
        ///  &lt;/archives&gt;
        ///  &lt;backup_dirs&gt;
        ///    &lt;backup&gt;param&lt;/backup&gt;
        ///    &lt;backup&gt;sfx&lt;/backup&gt;
        ///    &lt;backup&gt;sfx_lq&lt;/backup&gt;
        ///    &lt;backup&gt;sound&lt;/backup&gt;
        ///  &lt;/backup_dirs&gt;
        ///  &lt;delete_dirs&gt;
        ///    &lt;delete&gt;_unknown&lt;/delete&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScholarGameInfo {
            get {
                return ResourceManager.GetString("ScholarGameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /action/eventnameid.txt
        ////action/script/c0000.hks
        ////action/script/c0001.hks
        ////action/script/c0002.hks
        ////action/script/c0004.hks
        ////action/script/c0006.hks
        ////action/script/c0100.hks
        ////action/script/c1030.hks
        ////action/script/c1040.hks
        ////action/script/c1041.hks
        ////action/script/c1050.hks
        ////action/script/c1060.hks
        ////action/script/c1070.hks
        ////action/script/c1090.hks
        ////action/script/c1100.hks
        ////action/script/c1105.hks
        ////action/script/c1110.hks
        ////action/script/c1120.hks
        ////action/script/c1130.hks
        ////action/script/c113 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SekiroDictionary {
            get {
                return ResourceManager.GetString("SekiroDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;game_info&gt;
        ///  &lt;required_gb&gt;25&lt;/required_gb&gt;
        ///  &lt;bhd5_game&gt;Sekiro&lt;/bhd5_game&gt;
        ///  &lt;archives&gt;
        ///    &lt;archive&gt;Data1&lt;/archive&gt;
        ///    &lt;archive&gt;Data2&lt;/archive&gt;
        ///    &lt;archive&gt;Data3&lt;/archive&gt;
        ///    &lt;archive&gt;Data4&lt;/archive&gt;
        ///    &lt;archive&gt;Data5&lt;/archive&gt;
        ///  &lt;/archives&gt;
        ///  &lt;backup_dirs&gt;
        ///    &lt;backup&gt;sound&lt;/backup&gt;
        ///  &lt;/backup_dirs&gt;
        ///  &lt;delete_dirs&gt;
        ///    &lt;delete&gt;_unknown&lt;/delete&gt;
        ///    &lt;delete&gt;action&lt;/delete&gt;
        ///    &lt;delete&gt;adhoc&lt;/delete&gt;
        ///    &lt;delete&gt;chr&lt;/delete&gt;
        ///    &lt;delete&gt;event&lt;/d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SekiroGameInfo {
            get {
                return ResourceManager.GetString("SekiroGameInfo", resourceCulture);
            }
        }
    }
}
